// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/calculator-layouts/AccessibilityFirst.tsx": () => import("../components/mockups/calculator-layouts/AccessibilityFirst.tsx"),
  "./components/mockups/calculator-layouts/AffordanceFirst.tsx": () => import("../components/mockups/calculator-layouts/AffordanceFirst.tsx"),
  "./components/mockups/calculator-layouts/DecisionTree.tsx": () => import("../components/mockups/calculator-layouts/DecisionTree.tsx"),
  "./components/mockups/calculator-layouts/HierarchyFirst.tsx": () => import("../components/mockups/calculator-layouts/HierarchyFirst.tsx"),
  "./components/mockups/calculator-layouts/QuoteHero.tsx": () => import("../components/mockups/calculator-layouts/QuoteHero.tsx"),
  "./components/mockups/calculator-layouts/SpreadsheetView.tsx": () => import("../components/mockups/calculator-layouts/SpreadsheetView.tsx"),
  "./components/mockups/odoo-calculator/InvestmentBrandPitch.tsx": () => import("../components/mockups/odoo-calculator/InvestmentBrandPitch.tsx"),
  "./components/mockups/odoo-calculator/InvestmentCompact.tsx": () => import("../components/mockups/odoo-calculator/InvestmentCompact.tsx")
};
