// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/calculator-layouts/AccessibilityFirst.tsx": () => import("../components/mockups/calculator-layouts/AccessibilityFirst.tsx"),
  "./components/mockups/calculator-layouts/AffordanceFirst.tsx": () => import("../components/mockups/calculator-layouts/AffordanceFirst.tsx"),
  "./components/mockups/calculator-layouts/DecisionTree.tsx": () => import("../components/mockups/calculator-layouts/DecisionTree.tsx"),
  "./components/mockups/calculator-layouts/HierarchyFirst.tsx": () => import("../components/mockups/calculator-layouts/HierarchyFirst.tsx"),
  "./components/mockups/calculator-layouts/QuoteHero.tsx": () => import("../components/mockups/calculator-layouts/QuoteHero.tsx"),
  "./components/mockups/calculator-layouts/SpreadsheetView.tsx": () => import("../components/mockups/calculator-layouts/SpreadsheetView.tsx"),
  "./components/mockups/odoo-calculator/Investment.tsx": () => import("../components/mockups/odoo-calculator/Investment.tsx"),
  "./components/mockups/odoo-calculator/InvestmentCompact.tsx": () => import("../components/mockups/odoo-calculator/InvestmentCompact.tsx"),
  "./components/mockups/odoo-calculator/InvestmentDark.tsx": () => import("../components/mockups/odoo-calculator/InvestmentDark.tsx"),
  "./components/mockups/odoo-calculator/InvestmentEditorial.tsx": () => import("../components/mockups/odoo-calculator/InvestmentEditorial.tsx"),
  "./components/mockups/odoo-calculator/InvestmentLetterhead.tsx": () => import("../components/mockups/odoo-calculator/InvestmentLetterhead.tsx"),
  "./components/mockups/odoo-calculator/InvestmentMonogram.tsx": () => import("../components/mockups/odoo-calculator/InvestmentMonogram.tsx")
};
